/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttributeDTOPagedResponse } from './ChallengeAttributeDTOPagedResponse';
import {
    ChallengeAttributeDTOPagedResponseFromJSON,
    ChallengeAttributeDTOPagedResponseFromJSONTyped,
    ChallengeAttributeDTOPagedResponseToJSON,
} from './ChallengeAttributeDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeAttributeDTOPagedResponseRequestResponse
 */
export interface ChallengeAttributeDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ChallengeAttributeDTOPagedResponse}
     * @memberof ChallengeAttributeDTOPagedResponseRequestResponse
     */
    response?: ChallengeAttributeDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeAttributeDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeAttributeDTOPagedResponseRequestResponse interface.
 */
export function instanceOfChallengeAttributeDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeDTOPagedResponseRequestResponseFromJSON(json: any): ChallengeAttributeDTOPagedResponseRequestResponse {
    return ChallengeAttributeDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ChallengeAttributeDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeAttributeDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeAttributeDTOPagedResponseRequestResponseToJSON(value?: ChallengeAttributeDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeAttributeDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

