/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeProgressDTO } from './ChallengeProgressDTO';
import {
    ChallengeProgressDTOFromJSON,
    ChallengeProgressDTOFromJSONTyped,
    ChallengeProgressDTOToJSON,
} from './ChallengeProgressDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeProgressDTORequestResponse
 */
export interface ChallengeProgressDTORequestResponse {
    /**
     * 
     * @type {ChallengeProgressDTO}
     * @memberof ChallengeProgressDTORequestResponse
     */
    response?: ChallengeProgressDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeProgressDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeProgressDTORequestResponse interface.
 */
export function instanceOfChallengeProgressDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressDTORequestResponseFromJSON(json: any): ChallengeProgressDTORequestResponse {
    return ChallengeProgressDTORequestResponseFromJSONTyped(json, false);
}

export function ChallengeProgressDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgressDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeProgressDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeProgressDTORequestResponseToJSON(value?: ChallengeProgressDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeProgressDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

