/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeProgressUpdateDTO
 */
export interface ChallengeProgressUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressUpdateDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressUpdateDTO
     */
    challengeId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengeProgressUpdateDTO
     */
    isCompleted?: boolean;
}

/**
 * Check if a given object implements the ChallengeProgressUpdateDTO interface.
 */
export function instanceOfChallengeProgressUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressUpdateDTOFromJSON(json: any): ChallengeProgressUpdateDTO {
    return ChallengeProgressUpdateDTOFromJSONTyped(json, false);
}

export function ChallengeProgressUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgressUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'challengeId': !exists(json, 'challengeId') ? undefined : json['challengeId'],
        'isCompleted': !exists(json, 'isCompleted') ? undefined : json['isCompleted'],
    };
}

export function ChallengeProgressUpdateDTOToJSON(value?: ChallengeProgressUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'challengeId': value.challengeId,
        'isCompleted': value.isCompleted,
    };
}

