/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttributeWithScoresDTO } from './ChallengeAttributeWithScoresDTO';
import {
    ChallengeAttributeWithScoresDTOFromJSON,
    ChallengeAttributeWithScoresDTOFromJSONTyped,
    ChallengeAttributeWithScoresDTOToJSON,
} from './ChallengeAttributeWithScoresDTO';

/**
 * 
 * @export
 * @interface ChallengeAttributeWithScoresDTOPagedResponse
 */
export interface ChallengeAttributeWithScoresDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeWithScoresDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeWithScoresDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeWithScoresDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ChallengeAttributeWithScoresDTO>}
     * @memberof ChallengeAttributeWithScoresDTOPagedResponse
     */
    data?: Array<ChallengeAttributeWithScoresDTO> | null;
}

/**
 * Check if a given object implements the ChallengeAttributeWithScoresDTOPagedResponse interface.
 */
export function instanceOfChallengeAttributeWithScoresDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeWithScoresDTOPagedResponseFromJSON(json: any): ChallengeAttributeWithScoresDTOPagedResponse {
    return ChallengeAttributeWithScoresDTOPagedResponseFromJSONTyped(json, false);
}

export function ChallengeAttributeWithScoresDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeWithScoresDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ChallengeAttributeWithScoresDTOFromJSON)),
    };
}

export function ChallengeAttributeWithScoresDTOPagedResponseToJSON(value?: ChallengeAttributeWithScoresDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ChallengeAttributeWithScoresDTOToJSON)),
    };
}

