/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeProgressPagedResponse } from './ChallengeProgressPagedResponse';
import {
    ChallengeProgressPagedResponseFromJSON,
    ChallengeProgressPagedResponseFromJSONTyped,
    ChallengeProgressPagedResponseToJSON,
} from './ChallengeProgressPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeProgressPagedResponseRequestResponse
 */
export interface ChallengeProgressPagedResponseRequestResponse {
    /**
     * 
     * @type {ChallengeProgressPagedResponse}
     * @memberof ChallengeProgressPagedResponseRequestResponse
     */
    response?: ChallengeProgressPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeProgressPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeProgressPagedResponseRequestResponse interface.
 */
export function instanceOfChallengeProgressPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressPagedResponseRequestResponseFromJSON(json: any): ChallengeProgressPagedResponseRequestResponse {
    return ChallengeProgressPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ChallengeProgressPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgressPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeProgressPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeProgressPagedResponseRequestResponseToJSON(value?: ChallengeProgressPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeProgressPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

