/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeAttributeAddDTO
 */
export interface ChallengeAttributeAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeAttributeAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeAddDTO
     */
    points?: number;
}

/**
 * Check if a given object implements the ChallengeAttributeAddDTO interface.
 */
export function instanceOfChallengeAttributeAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeAddDTOFromJSON(json: any): ChallengeAttributeAddDTO {
    return ChallengeAttributeAddDTOFromJSONTyped(json, false);
}

export function ChallengeAttributeAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'points': !exists(json, 'points') ? undefined : json['points'],
    };
}

export function ChallengeAttributeAddDTOToJSON(value?: ChallengeAttributeAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'points': value.points,
    };
}

