/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeDTO } from './ChallengeDTO';
import {
    ChallengeDTOFromJSON,
    ChallengeDTOFromJSONTyped,
    ChallengeDTOToJSON,
} from './ChallengeDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeDTORequestResponse
 */
export interface ChallengeDTORequestResponse {
    /**
     * 
     * @type {ChallengeDTO}
     * @memberof ChallengeDTORequestResponse
     */
    response?: ChallengeDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeDTORequestResponse interface.
 */
export function instanceOfChallengeDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeDTORequestResponseFromJSON(json: any): ChallengeDTORequestResponse {
    return ChallengeDTORequestResponseFromJSONTyped(json, false);
}

export function ChallengeDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeDTORequestResponseToJSON(value?: ChallengeDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

