/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeProgressDetailedDTOPagedResponse } from './ChallengeProgressDetailedDTOPagedResponse';
import {
    ChallengeProgressDetailedDTOPagedResponseFromJSON,
    ChallengeProgressDetailedDTOPagedResponseFromJSONTyped,
    ChallengeProgressDetailedDTOPagedResponseToJSON,
} from './ChallengeProgressDetailedDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeProgressDetailedDTOPagedResponseRequestResponse
 */
export interface ChallengeProgressDetailedDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ChallengeProgressDetailedDTOPagedResponse}
     * @memberof ChallengeProgressDetailedDTOPagedResponseRequestResponse
     */
    response?: ChallengeProgressDetailedDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeProgressDetailedDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeProgressDetailedDTOPagedResponseRequestResponse interface.
 */
export function instanceOfChallengeProgressDetailedDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressDetailedDTOPagedResponseRequestResponseFromJSON(json: any): ChallengeProgressDetailedDTOPagedResponseRequestResponse {
    return ChallengeProgressDetailedDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ChallengeProgressDetailedDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgressDetailedDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeProgressDetailedDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeProgressDetailedDTOPagedResponseRequestResponseToJSON(value?: ChallengeProgressDetailedDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeProgressDetailedDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

