/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScoreWithUserDTO } from './ScoreWithUserDTO';
import {
    ScoreWithUserDTOFromJSON,
    ScoreWithUserDTOFromJSONTyped,
    ScoreWithUserDTOToJSON,
} from './ScoreWithUserDTO';

/**
 * 
 * @export
 * @interface ChallengeAttributeWithScoresDTO
 */
export interface ChallengeAttributeWithScoresDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeAttributeWithScoresDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeAttributeWithScoresDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeWithScoresDTO
     */
    points?: number;
    /**
     * 
     * @type {Array<ScoreWithUserDTO>}
     * @memberof ChallengeAttributeWithScoresDTO
     */
    scores?: Array<ScoreWithUserDTO> | null;
}

/**
 * Check if a given object implements the ChallengeAttributeWithScoresDTO interface.
 */
export function instanceOfChallengeAttributeWithScoresDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeWithScoresDTOFromJSON(json: any): ChallengeAttributeWithScoresDTO {
    return ChallengeAttributeWithScoresDTOFromJSONTyped(json, false);
}

export function ChallengeAttributeWithScoresDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeWithScoresDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'points': !exists(json, 'points') ? undefined : json['points'],
        'scores': !exists(json, 'scores') ? undefined : (json['scores'] === null ? null : (json['scores'] as Array<any>).map(ScoreWithUserDTOFromJSON)),
    };
}

export function ChallengeAttributeWithScoresDTOToJSON(value?: ChallengeAttributeWithScoresDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'points': value.points,
        'scores': value.scores === undefined ? undefined : (value.scores === null ? null : (value.scores as Array<any>).map(ScoreWithUserDTOToJSON)),
    };
}

