/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Challenge } from './Challenge';
import {
    ChallengeFromJSON,
    ChallengeFromJSONTyped,
    ChallengeToJSON,
} from './Challenge';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ChallengeProgress
 */
export interface ChallengeProgress {
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgress
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChallengeProgress
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChallengeProgress
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgress
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgress
     */
    challengeId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengeProgress
     */
    isCompleted?: boolean;
    /**
     * 
     * @type {User}
     * @memberof ChallengeProgress
     */
    user?: User;
    /**
     * 
     * @type {Challenge}
     * @memberof ChallengeProgress
     */
    challenge?: Challenge;
}

/**
 * Check if a given object implements the ChallengeProgress interface.
 */
export function instanceOfChallengeProgress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressFromJSON(json: any): ChallengeProgress {
    return ChallengeProgressFromJSONTyped(json, false);
}

export function ChallengeProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'challengeId': !exists(json, 'challengeId') ? undefined : json['challengeId'],
        'isCompleted': !exists(json, 'isCompleted') ? undefined : json['isCompleted'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'challenge': !exists(json, 'challenge') ? undefined : ChallengeFromJSON(json['challenge']),
    };
}

export function ChallengeProgressToJSON(value?: ChallengeProgress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'userId': value.userId,
        'challengeId': value.challengeId,
        'isCompleted': value.isCompleted,
        'user': UserToJSON(value.user),
        'challenge': ChallengeToJSON(value.challenge),
    };
}

