/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeWithAttributesAddDTO
 */
export interface ChallengeWithAttributesAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeWithAttributesAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChallengeWithAttributesAddDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChallengeWithAttributesAddDTO
     */
    challengeAttributeNames?: string | null;
}

/**
 * Check if a given object implements the ChallengeWithAttributesAddDTO interface.
 */
export function instanceOfChallengeWithAttributesAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeWithAttributesAddDTOFromJSON(json: any): ChallengeWithAttributesAddDTO {
    return ChallengeWithAttributesAddDTOFromJSONTyped(json, false);
}

export function ChallengeWithAttributesAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeWithAttributesAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'challengeAttributeNames': !exists(json, 'challengeAttributeNames') ? undefined : json['challengeAttributeNames'],
    };
}

export function ChallengeWithAttributesAddDTOToJSON(value?: ChallengeWithAttributesAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'challengeAttributeNames': value.challengeAttributeNames,
    };
}

