/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeProgressAddDTO
 */
export interface ChallengeProgressAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressAddDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressAddDTO
     */
    challengeId?: string;
}

/**
 * Check if a given object implements the ChallengeProgressAddDTO interface.
 */
export function instanceOfChallengeProgressAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressAddDTOFromJSON(json: any): ChallengeProgressAddDTO {
    return ChallengeProgressAddDTOFromJSONTyped(json, false);
}

export function ChallengeProgressAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgressAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'challengeId': !exists(json, 'challengeId') ? undefined : json['challengeId'],
    };
}

export function ChallengeProgressAddDTOToJSON(value?: ChallengeProgressAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'challengeId': value.challengeId,
    };
}

