/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeDTOPagedResponse } from './ChallengeDTOPagedResponse';
import {
    ChallengeDTOPagedResponseFromJSON,
    ChallengeDTOPagedResponseFromJSONTyped,
    ChallengeDTOPagedResponseToJSON,
} from './ChallengeDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeDTOPagedResponseRequestResponse
 */
export interface ChallengeDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ChallengeDTOPagedResponse}
     * @memberof ChallengeDTOPagedResponseRequestResponse
     */
    response?: ChallengeDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeDTOPagedResponseRequestResponse interface.
 */
export function instanceOfChallengeDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeDTOPagedResponseRequestResponseFromJSON(json: any): ChallengeDTOPagedResponseRequestResponse {
    return ChallengeDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ChallengeDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeDTOPagedResponseRequestResponseToJSON(value?: ChallengeDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

