/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttributeDTO } from './ChallengeAttributeDTO';
import {
    ChallengeAttributeDTOFromJSON,
    ChallengeAttributeDTOFromJSONTyped,
    ChallengeAttributeDTOToJSON,
} from './ChallengeAttributeDTO';

/**
 * 
 * @export
 * @interface ChallengeAttributeDTOPagedResponse
 */
export interface ChallengeAttributeDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ChallengeAttributeDTO>}
     * @memberof ChallengeAttributeDTOPagedResponse
     */
    data?: Array<ChallengeAttributeDTO> | null;
}

/**
 * Check if a given object implements the ChallengeAttributeDTOPagedResponse interface.
 */
export function instanceOfChallengeAttributeDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeDTOPagedResponseFromJSON(json: any): ChallengeAttributeDTOPagedResponse {
    return ChallengeAttributeDTOPagedResponseFromJSONTyped(json, false);
}

export function ChallengeAttributeDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ChallengeAttributeDTOFromJSON)),
    };
}

export function ChallengeAttributeDTOPagedResponseToJSON(value?: ChallengeAttributeDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ChallengeAttributeDTOToJSON)),
    };
}

