/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeAddDTO
 */
export interface ChallengeAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChallengeAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ChallengeAddDTO interface.
 */
export function instanceOfChallengeAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAddDTOFromJSON(json: any): ChallengeAddDTO {
    return ChallengeAddDTOFromJSONTyped(json, false);
}

export function ChallengeAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ChallengeAddDTOToJSON(value?: ChallengeAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
    };
}

