/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeAttributeUpdateDTO
 */
export interface ChallengeAttributeUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeAttributeUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeAttributeUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChallengeAttributeUpdateDTO
     */
    points?: number | null;
}

/**
 * Check if a given object implements the ChallengeAttributeUpdateDTO interface.
 */
export function instanceOfChallengeAttributeUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeUpdateDTOFromJSON(json: any): ChallengeAttributeUpdateDTO {
    return ChallengeAttributeUpdateDTOFromJSONTyped(json, false);
}

export function ChallengeAttributeUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'points': !exists(json, 'points') ? undefined : json['points'],
    };
}

export function ChallengeAttributeUpdateDTOToJSON(value?: ChallengeAttributeUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'points': value.points,
    };
}

