/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttribute } from './ChallengeAttribute';
import {
    ChallengeAttributeFromJSON,
    ChallengeAttributeFromJSONTyped,
    ChallengeAttributeToJSON,
} from './ChallengeAttribute';
import type { ChallengeProgress } from './ChallengeProgress';
import {
    ChallengeProgressFromJSON,
    ChallengeProgressFromJSONTyped,
    ChallengeProgressToJSON,
} from './ChallengeProgress';

/**
 * 
 * @export
 * @interface Challenge
 */
export interface Challenge {
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Challenge
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Challenge
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    description?: string | null;
    /**
     * 
     * @type {Array<ChallengeAttribute>}
     * @memberof Challenge
     */
    challengeAttributes?: Array<ChallengeAttribute> | null;
    /**
     * 
     * @type {Array<ChallengeProgress>}
     * @memberof Challenge
     */
    challengesProgress?: Array<ChallengeProgress> | null;
}

/**
 * Check if a given object implements the Challenge interface.
 */
export function instanceOfChallenge(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeFromJSON(json: any): Challenge {
    return ChallengeFromJSONTyped(json, false);
}

export function ChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Challenge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'challengeAttributes': !exists(json, 'challengeAttributes') ? undefined : (json['challengeAttributes'] === null ? null : (json['challengeAttributes'] as Array<any>).map(ChallengeAttributeFromJSON)),
        'challengesProgress': !exists(json, 'challengesProgress') ? undefined : (json['challengesProgress'] === null ? null : (json['challengesProgress'] as Array<any>).map(ChallengeProgressFromJSON)),
    };
}

export function ChallengeToJSON(value?: Challenge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'title': value.title,
        'description': value.description,
        'challengeAttributes': value.challengeAttributes === undefined ? undefined : (value.challengeAttributes === null ? null : (value.challengeAttributes as Array<any>).map(ChallengeAttributeToJSON)),
        'challengesProgress': value.challengesProgress === undefined ? undefined : (value.challengesProgress === null ? null : (value.challengesProgress as Array<any>).map(ChallengeProgressToJSON)),
    };
}

