/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttributeDTO } from './ChallengeAttributeDTO';
import {
    ChallengeAttributeDTOFromJSON,
    ChallengeAttributeDTOFromJSONTyped,
    ChallengeAttributeDTOToJSON,
} from './ChallengeAttributeDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeAttributeDTORequestResponse
 */
export interface ChallengeAttributeDTORequestResponse {
    /**
     * 
     * @type {ChallengeAttributeDTO}
     * @memberof ChallengeAttributeDTORequestResponse
     */
    response?: ChallengeAttributeDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeAttributeDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeAttributeDTORequestResponse interface.
 */
export function instanceOfChallengeAttributeDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeAttributeDTORequestResponseFromJSON(json: any): ChallengeAttributeDTORequestResponse {
    return ChallengeAttributeDTORequestResponseFromJSONTyped(json, false);
}

export function ChallengeAttributeDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeAttributeDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeAttributeDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeAttributeDTORequestResponseToJSON(value?: ChallengeAttributeDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeAttributeDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

