/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Challenge } from './Challenge';
import {
    ChallengeFromJSON,
    ChallengeFromJSONTyped,
    ChallengeToJSON,
} from './Challenge';

/**
 * 
 * @export
 * @interface ChallengeProgressDetailedDTO
 */
export interface ChallengeProgressDetailedDTO {
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressDetailedDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressDetailedDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeProgressDetailedDTO
     */
    challengeId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChallengeProgressDetailedDTO
     */
    isCompleted?: boolean;
    /**
     * 
     * @type {Challenge}
     * @memberof ChallengeProgressDetailedDTO
     */
    challenge?: Challenge;
}

/**
 * Check if a given object implements the ChallengeProgressDetailedDTO interface.
 */
export function instanceOfChallengeProgressDetailedDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeProgressDetailedDTOFromJSON(json: any): ChallengeProgressDetailedDTO {
    return ChallengeProgressDetailedDTOFromJSONTyped(json, false);
}

export function ChallengeProgressDetailedDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeProgressDetailedDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'challengeId': !exists(json, 'challengeId') ? undefined : json['challengeId'],
        'isCompleted': !exists(json, 'isCompleted') ? undefined : json['isCompleted'],
        'challenge': !exists(json, 'challenge') ? undefined : ChallengeFromJSON(json['challenge']),
    };
}

export function ChallengeProgressDetailedDTOToJSON(value?: ChallengeProgressDetailedDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'challengeId': value.challengeId,
        'isCompleted': value.isCompleted,
        'challenge': ChallengeToJSON(value.challenge),
    };
}

