/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeWithAttributesDTO } from './ChallengeWithAttributesDTO';
import {
    ChallengeWithAttributesDTOFromJSON,
    ChallengeWithAttributesDTOFromJSONTyped,
    ChallengeWithAttributesDTOToJSON,
} from './ChallengeWithAttributesDTO';

/**
 * 
 * @export
 * @interface ChallengeWithAttributesDTOPagedResponse
 */
export interface ChallengeWithAttributesDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ChallengeWithAttributesDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengeWithAttributesDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ChallengeWithAttributesDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ChallengeWithAttributesDTO>}
     * @memberof ChallengeWithAttributesDTOPagedResponse
     */
    data?: Array<ChallengeWithAttributesDTO> | null;
}

/**
 * Check if a given object implements the ChallengeWithAttributesDTOPagedResponse interface.
 */
export function instanceOfChallengeWithAttributesDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeWithAttributesDTOPagedResponseFromJSON(json: any): ChallengeWithAttributesDTOPagedResponse {
    return ChallengeWithAttributesDTOPagedResponseFromJSONTyped(json, false);
}

export function ChallengeWithAttributesDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeWithAttributesDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ChallengeWithAttributesDTOFromJSON)),
    };
}

export function ChallengeWithAttributesDTOPagedResponseToJSON(value?: ChallengeWithAttributesDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ChallengeWithAttributesDTOToJSON)),
    };
}

