/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeWithAttributesDTOPagedResponse } from './ChallengeWithAttributesDTOPagedResponse';
import {
    ChallengeWithAttributesDTOPagedResponseFromJSON,
    ChallengeWithAttributesDTOPagedResponseFromJSONTyped,
    ChallengeWithAttributesDTOPagedResponseToJSON,
} from './ChallengeWithAttributesDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ChallengeWithAttributesDTOPagedResponseRequestResponse
 */
export interface ChallengeWithAttributesDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ChallengeWithAttributesDTOPagedResponse}
     * @memberof ChallengeWithAttributesDTOPagedResponseRequestResponse
     */
    response?: ChallengeWithAttributesDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ChallengeWithAttributesDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ChallengeWithAttributesDTOPagedResponseRequestResponse interface.
 */
export function instanceOfChallengeWithAttributesDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChallengeWithAttributesDTOPagedResponseRequestResponseFromJSON(json: any): ChallengeWithAttributesDTOPagedResponseRequestResponse {
    return ChallengeWithAttributesDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ChallengeWithAttributesDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeWithAttributesDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ChallengeWithAttributesDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ChallengeWithAttributesDTOPagedResponseRequestResponseToJSON(value?: ChallengeWithAttributesDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ChallengeWithAttributesDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

