/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttribute } from './ChallengeAttribute';
import {
    ChallengeAttributeFromJSON,
    ChallengeAttributeFromJSONTyped,
    ChallengeAttributeToJSON,
} from './ChallengeAttribute';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Score
 */
export interface Score {
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Score
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Score
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    attributeId?: string;
    /**
     * 
     * @type {number}
     * @memberof Score
     */
    scorePoints?: number;
    /**
     * 
     * @type {User}
     * @memberof Score
     */
    user?: User;
    /**
     * 
     * @type {ChallengeAttribute}
     * @memberof Score
     */
    challengeAttribute?: ChallengeAttribute;
}

/**
 * Check if a given object implements the Score interface.
 */
export function instanceOfScore(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScoreFromJSON(json: any): Score {
    return ScoreFromJSONTyped(json, false);
}

export function ScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Score {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'attributeId': !exists(json, 'attributeId') ? undefined : json['attributeId'],
        'scorePoints': !exists(json, 'scorePoints') ? undefined : json['scorePoints'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'challengeAttribute': !exists(json, 'challengeAttribute') ? undefined : ChallengeAttributeFromJSON(json['challengeAttribute']),
    };
}

export function ScoreToJSON(value?: Score | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'userId': value.userId,
        'attributeId': value.attributeId,
        'scorePoints': value.scorePoints,
        'user': UserToJSON(value.user),
        'challengeAttribute': ChallengeAttributeToJSON(value.challengeAttribute),
    };
}

