/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreDTO
 */
export interface ScoreDTO {
    /**
     * 
     * @type {string}
     * @memberof ScoreDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ScoreDTO
     */
    scorePoints?: number;
    /**
     * 
     * @type {string}
     * @memberof ScoreDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ScoreDTO
     */
    attributeId?: string;
}

/**
 * Check if a given object implements the ScoreDTO interface.
 */
export function instanceOfScoreDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScoreDTOFromJSON(json: any): ScoreDTO {
    return ScoreDTOFromJSONTyped(json, false);
}

export function ScoreDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'scorePoints': !exists(json, 'scorePoints') ? undefined : json['scorePoints'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'attributeId': !exists(json, 'attributeId') ? undefined : json['attributeId'],
    };
}

export function ScoreDTOToJSON(value?: ScoreDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'scorePoints': value.scorePoints,
        'userId': value.userId,
        'attributeId': value.attributeId,
    };
}

