/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScoreWithAttributeDTO } from './ScoreWithAttributeDTO';
import {
    ScoreWithAttributeDTOFromJSON,
    ScoreWithAttributeDTOFromJSONTyped,
    ScoreWithAttributeDTOToJSON,
} from './ScoreWithAttributeDTO';

/**
 * 
 * @export
 * @interface ScoreWithAttributeDTOPagedResponse
 */
export interface ScoreWithAttributeDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ScoreWithAttributeDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ScoreWithAttributeDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ScoreWithAttributeDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ScoreWithAttributeDTO>}
     * @memberof ScoreWithAttributeDTOPagedResponse
     */
    data?: Array<ScoreWithAttributeDTO> | null;
}

/**
 * Check if a given object implements the ScoreWithAttributeDTOPagedResponse interface.
 */
export function instanceOfScoreWithAttributeDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScoreWithAttributeDTOPagedResponseFromJSON(json: any): ScoreWithAttributeDTOPagedResponse {
    return ScoreWithAttributeDTOPagedResponseFromJSONTyped(json, false);
}

export function ScoreWithAttributeDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreWithAttributeDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ScoreWithAttributeDTOFromJSON)),
    };
}

export function ScoreWithAttributeDTOPagedResponseToJSON(value?: ScoreWithAttributeDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ScoreWithAttributeDTOToJSON)),
    };
}

