/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChallengeAttribute } from './ChallengeAttribute';
import {
    ChallengeAttributeFromJSON,
    ChallengeAttributeFromJSONTyped,
    ChallengeAttributeToJSON,
} from './ChallengeAttribute';

/**
 * 
 * @export
 * @interface ScoreWithAttributeDTO
 */
export interface ScoreWithAttributeDTO {
    /**
     * 
     * @type {string}
     * @memberof ScoreWithAttributeDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ScoreWithAttributeDTO
     */
    scorePoints?: number;
    /**
     * 
     * @type {string}
     * @memberof ScoreWithAttributeDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ScoreWithAttributeDTO
     */
    attributeId?: string;
    /**
     * 
     * @type {ChallengeAttribute}
     * @memberof ScoreWithAttributeDTO
     */
    challengeAttribute?: ChallengeAttribute;
}

/**
 * Check if a given object implements the ScoreWithAttributeDTO interface.
 */
export function instanceOfScoreWithAttributeDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScoreWithAttributeDTOFromJSON(json: any): ScoreWithAttributeDTO {
    return ScoreWithAttributeDTOFromJSONTyped(json, false);
}

export function ScoreWithAttributeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreWithAttributeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'scorePoints': !exists(json, 'scorePoints') ? undefined : json['scorePoints'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'attributeId': !exists(json, 'attributeId') ? undefined : json['attributeId'],
        'challengeAttribute': !exists(json, 'challengeAttribute') ? undefined : ChallengeAttributeFromJSON(json['challengeAttribute']),
    };
}

export function ScoreWithAttributeDTOToJSON(value?: ScoreWithAttributeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'scorePoints': value.scorePoints,
        'userId': value.userId,
        'attributeId': value.attributeId,
        'challengeAttribute': ChallengeAttributeToJSON(value.challengeAttribute),
    };
}

