/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ScoreWithUserDTO
 */
export interface ScoreWithUserDTO {
    /**
     * 
     * @type {string}
     * @memberof ScoreWithUserDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ScoreWithUserDTO
     */
    scorePoints?: number;
    /**
     * 
     * @type {string}
     * @memberof ScoreWithUserDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ScoreWithUserDTO
     */
    attributeId?: string;
    /**
     * 
     * @type {User}
     * @memberof ScoreWithUserDTO
     */
    user?: User;
}

/**
 * Check if a given object implements the ScoreWithUserDTO interface.
 */
export function instanceOfScoreWithUserDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScoreWithUserDTOFromJSON(json: any): ScoreWithUserDTO {
    return ScoreWithUserDTOFromJSONTyped(json, false);
}

export function ScoreWithUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreWithUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'scorePoints': !exists(json, 'scorePoints') ? undefined : json['scorePoints'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'attributeId': !exists(json, 'attributeId') ? undefined : json['attributeId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function ScoreWithUserDTOToJSON(value?: ScoreWithUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'scorePoints': value.scorePoints,
        'userId': value.userId,
        'attributeId': value.attributeId,
        'user': UserToJSON(value.user),
    };
}

